import type { IBCCAccountGender } from "@bankeiro/bankeiro-backend-corecard";

export interface ICardHolderDTO {
  produto: string;
  codigoEntregadora: string;
  tipoCartao: string;
  codigoPlastico: string;
  tipoPlastico: string;
  codigoEmpregador: number;
  nomeEmpregador: string;
  matricula: string;
  cargo: string;
  dataAdmissao: string;
  salario?: number;
  limiteCredito?: string;
  geraSenhaAtivacao: string;
  nomeCompleto: string;
  nome: string;
  sobreNome: string;
  nomeSocial: string;
  dataNascimento: string;
  sexo: IBCCAccountGender;
  estadoCivil: string;
  nacionalidade: string;
  cpf: string;
  rg: string;
  orgaoEmissorRG: string;
  estadoEmissorRG: string;
  nomePai: string;
  nomeMae: string;
  ga?: string;
  logradouro?: string;
  numero: string;
  complemento?: string;
  referencia?: string;
  bairro: string;
  cep: number;
  cidade: string;
  estado: string;
  pais: string;
  telefone: string;
  telefoneComercial?: string;
  celular?: string;
  email: string;
  proxy?: string;
  codigoBanco?: string;
  codigoAgencia?: string;
  codigoContaCorrente?: string;
  digitoContaCorrente?: string;
  codigoVencimentoFatura: string;
  tipoEnvioFatura: string;
  cnpjCorrespondente?: string;
  geraEmbossing: string;
  embossadora: string;
  permiteAssociacaoMultipla?: boolean;
  RMC?: string;
}

export type IAddCardHolderDTO = ICardHolderDTO;

export type CardHolderCreateRes = {
  cartao: string;
  proxy: string;
  dataVencimento: string;
  nomeEmbossing: string;
  conta: string;
};

export type IAddCardHolderResDTO = CardHolderCreateRes;
export type ICreateCardHolderResponse = CardHolderCreateRes;
export type INewPortadorResDTO = CardHolderCreateRes;

export interface IUpdateCardHolderDTO {
  nomeCompleto: string;
  nome: string;
  sobrenome: string;
  nomeEmbossing: string;
  dataNascimento: string;
  sexo: "M" | "F" | "S";
  estadoCivil: string;
  nacionalidade: string;
  documento: string;
  rg: string;
  orgaoEmissorRG: string;
  estadoEmissorRG: string;
  nomeMae: string;
  nomePai: string;
  logradouro: string;
  numero: string;
  complemento: string;
  referencia: string;
  bairro: string;
  cidade: string;
  estado: string;
  pais: string;
  cep: number;
  telefone: string;
  telefoneComercial: string;
  celular: string;
  email: string;
}

export type CardHolderCreateParams = {
  nome: string;
  nomeCompleto: string;
  sobreNome: string;
  dataNascimento: string;
  email: string;
  estadoCivil: string;
  nacionalidade: string;
  nomeMae: string;
  nomePai: string;
  nomeSocial: string;
  sexo: string;
  telefone: string;
  telefoneComercial: string;
  celular: string;
  cpf: string;
  rg: string;
  orgaoEmissorRG: string;
  estadoEmissorRG: string;
  logradouro: string;
  numero: string;
  complemento: string;
  referencia: string;
  bairro: string;
  cidade: string;
  cep: string;
  estado: string;
  pais: string;
  nomeEmpregador: string;
  codigoEmpregador: string;
  matricula: string;
  cargo: string;
  dataAdmissao: string;
  salario: string;
  produto: string;
  tipoCartao: string;
  ga: string;
  limiteCredito: string;
  embossadora: string;
  geraSenhaAtivacao: string;
  codigoEntregadora: string;
  codigoPlastico: string;
  codigoVencimentoFatura: string;
  geraEmbossing: string;
  tipoEnvioFatura: string;
  tipoPlastico: string;
  proxy: string;
  RMC: string;
  codigoBanco: string;
  codigoAgencia: string;
  codigoContaCorrente: string;
  digitoContaCorrente: string;
  cnpjCorrespondente: string;
};

export type ICreateCardHolderParams = CardHolderCreateParams;
export type INewPortadorDTO = CardHolderCreateParams;
